blueprint:
  name: PV Excess Load Controller with Forecast & Priority
  description: >
    Turns devices on/off based on excess PV, battery target (Sigenergy),
    and Solcast forecast. Supports priorities, minimum runtime, and logging.
  domain: automation

  input:
    pv_power:
      name: Current PV Power (W)
      selector:
        entity:
          domain: sensor

    house_load:
      name: Current House Load (W)
      selector:
        entity:
          domain: sensor

    battery_soc:
      name: Battery State of Charge (%)
      selector:
        entity:
          domain: sensor

    battery_target:
      name: Target Battery SoC (%)
      default: 90
      selector:
        number:
          min: 0
          max: 100

    solcast_forecast_remaining:
      name: Remaining Solar Forecast (kWh)
      selector:
        entity:
          domain: sensor

    battery_capacity_kwh:
      name: Battery Capacity (kWh)
      selector:
        number:
          min: 1
          max: 100

    loads:
      name: Load Devices
      description: Devices with power + priority
      selector:
        object:

    min_excess_power:
      name: Minimum Excess Power (W)
      default: 300
      selector:
        number:
          min: 0
          max: 10000

    check_interval:
      name: Check Interval
      default: "/30"
      selector:
        select:
          options:
            - "/10"
            - "/15"
            - "/30"
            - "/60"

mode: restart

trigger:
  - platform: time_pattern
    seconds: !input check_interval

variables:
  pv: "{{ states(input.pv_power) | float(0) }}"
  load: "{{ states(input.house_load) | float(0) }}"
  soc: "{{ states(input.battery_soc) | float(0) }}"
  forecast: "{{ states(input.solcast_forecast_remaining) | float(0) }}"
  target: "{{ input.battery_target | float }}"
  capacity: "{{ input.battery_capacity_kwh | float }}"

  excess_power: "{{ pv - load }}"

  required_energy:
    "{{ ((target - soc) / 100) * capacity }}"

  forecast_surplus:
    "{{ forecast - required_energy }}"

action:
  - variables:
      sorted_loads: >
        {{ dict(input.loads)
           | dictsort(by='value.priority')
           | map(attribute=1)
           | list }}

  - repeat:
      for_each: "{{ sorted_loads }}"
      sequence:
        - variables:
            entity: "{{ repeat.item.entity }}"
            power: "{{ repeat.item.power }}"
            priority: "{{ repeat.item.priority }}"
            min_runtime: "{{ repeat.item.min_runtime | default(0) }}"
            last_changed: "{{ states[entity].last_changed }}"
            runtime: >
              {{ (now() - last_changed).total_seconds() }}

        - choose:

            # TURN ON
            - conditions:
                - condition: template
                  value_template: >
                    {{ excess_power > power
                       and forecast_surplus > 0 }}
                - condition: template
                  value_template: >
                    {{ is_state(entity, 'off') }}

              sequence:
                - service: switch.turn_on
                  target:
                    entity_id: >
                      {{ entity }}

                - service: logbook.log
                  data:
                    name: PV Controller
                    message: >
                      Turned ON {{ entity }}
                      (Excess: {{ excess_power }}W,
                       Forecast surplus: {{ forecast_surplus }}kWh,
                       Priority: {{ priority }})

            # TURN OFF
            - conditions:
                - condition: template
                  value_template: >
                    {{ (excess_power < power
                        or forecast_surplus < 0) }}
                - condition: template
                  value_template: >
                    {{ is_state(entity, 'on') }}
                - condition: template
                  value_template: >
                    {{ runtime > min_runtime }}

              sequence:
                - service: switch.turn_off
                  target:
                    entity_id: >
                      {{ entity }}

                - service: logbook.log
                  data:
                    name: PV Controller
                    message: >
                      Turned OFF {{ entity }}
                      (Excess: {{ excess_power }}W,
                       Forecast surplus: {{ forecast_surplus }}kWh,
                       Runtime: {{ runtime }}s)
