blueprint:
  name: PV Smart Load (Per Device with Priority Awareness)
  description: >
    One automation per device. Uses PV excess, forecast, and
    respects higher priority loads.

  domain: automation

  input:
    target_device:
      name: Device
      selector:
        entity:
          domain: switch

    device_power:
      name: Device Power (W)
      selector:
        number:
          min: 0
          max: 10000

    higher_priority_devices:
      name: Higher Priority Devices
      description: Devices that must run before this one
      default: []
      selector:
        entity:
          multiple: true

    pv_power:
      selector:
        entity:
          domain: sensor

    house_load:
      selector:
        entity:
          domain: sensor

    battery_soc:
      selector:
        entity:
          domain: sensor

    battery_target:
      default: 90
      selector:
        number:
          min: 0
          max: 100

    solcast_forecast_remaining:
      selector:
        entity:
          domain: sensor

    battery_capacity_kwh:
      selector:
        number:
          min: 1
          max: 100

    min_runtime:
      default: 0
      selector:
        number:
          min: 0
          max: 7200

    check_interval:
      default: 1
      selector:
        number:
          min: 1
          max: 10

mode: restart

trigger:
  - platform: time_pattern
    minutes: "/1"

variables:
  pv: "{{ states(input.pv_power) | float(0) }}"
  load: "{{ states(input.house_load) | float(0) }}"
  soc: "{{ states(input.battery_soc) | float(0) }}"
  forecast: "{{ states(input.solcast_forecast_remaining) | float(0) }}"
  target: "{{ input.battery_target | float }}"
  capacity: "{{ input.battery_capacity_kwh | float }}"

  device: !input target_device
  device_power: !input device_power

  excess_power: "{{ pv - load }}"

  required_energy: >
    {{ ((target - soc) / 100) * capacity }}

  forecast_surplus: >
    {{ forecast - required_energy }}

  higher_running: >
    {{ expand(input.higher_priority_devices)
       | selectattr('state', 'eq', 'on')
       | list
       | count > 0 }}

  last_changed: "{{ states.get(device).last_changed }}"
  runtime: "{{ (now() - last_changed).total_seconds() }}"

action:

  # ⏱ Interval control
  - condition: template
    value_template: >
      {{ (now().minute % (input.check_interval | int)) == 0 }}

  - choose:

      # ✅ TURN ON
      - conditions:
          - condition: template
            value_template: >
              {{ excess_power > device_power
                 and forecast_surplus > 0
                 and not higher_running }}

          - condition: template
            value_template: >
              {{ is_state(device, 'off') }}

        sequence:
          - service: switch.turn_on
            target:
              entity_id: "{{ device }}"

          - service: logbook.log
            data:
              name: PV Device Controller
              message: >
                ON {{ device }}
                | Excess: {{ excess_power }}
                | Forecast OK
                | No higher priority loads active

      # ❌ TURN OFF
      - conditions:
          - condition: template
            value_template: >
              {{ excess_power < device_power
                 or forecast_surplus < 0
                 or higher_running }}

          - condition: template
            value_template: >
              {{ is_state(device, 'on') }}

          - condition: template
            value_template: >
              {{ runtime > min_runtime }}

        sequence:
          - service: switch.turn_off
            target:
              entity_id: "{{ device }}"

          - service: logbook.log
            data:
              name: PV Device Controller
              message: >
                OFF {{ device }}
                | Reason:
                {% if higher_running %}Higher priority active{% endif %}
                {% if forecast_surplus < 0 %} Forecast low{% endif %}
                {% if excess_power < device_power %} Not enough solar{% endif %}
